### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mdarab** [nvinayvarma189/Sitting-Posture-Recognition#3]
Hi Dear,

First of all, thank you for your helpful code on sitting posture recognition. I'm also working on a similar project.

I would like to improve the accuracy of body postures.

Could you please send me your dataset?

Best regards,

**Comment by nvinayvarma189** [comment]
Sorry I missed this completely. Thanks for reaching out. The openpose model has been trained on the [CMU Panoptic Studio dataset](http://domedb.perception.cs.cmu.edu/).
